global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "template-api"
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - host.docker.internal:7231

# bash
# docker run -d -p 9090:9090 -v %cd%/prometheus.yml:/etc/prometheus/prometheus.yml --name prometheus prom/prometheus
